/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package org.firstinspires.ftc.teamcode.testCode.odometryCoreTest;


import org.firstinspires.ftc.teamcode.testCode.odometryCoreTest.math.CoreMath;

public class OdometryCore {

    public void getOdometryCoordinate() {
        System.out.println(CoreMath.getHeading(17.606, 13.810, 7.25, 7.25));
    }
}
